// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LLMConfig holds the settings for the built-in AI agent's model provider.
 * The endpoint/model follow the OpenAI-compatible wire format, so DeepSeek,
 * Ollama and other compatible services all work by pointing the endpoint at
 * their base URL. An empty endpoint means "use the provider default".
 */
export interface LLMConfig {
    /**
     * Provider selects the provider implementation: "openaicompletions"
     * (default; any OpenAI-compatible endpoint) or "ollama".
     */
    "provider": string;

    /**
     * Endpoint is the provider's base URL (e.g.
     * https://api.deepseek.com/v1/chat/completions). Empty = provider default.
     */
    "endpoint": string;

    /**
     * Model is the model name to use (e.g. deepseek-chat, qwen2.5-coder).
     */
    "model": string;

    /**
     * APIKey is the API key for cloud providers; ignored by local providers.
     */
    "api_key": string;
}

/**
 * TabPref is the persisted UI state of one terminal tab (sessions themselves
 * are not restored — each tab boots a fresh shell on startup).
 */
export interface TabPref {
    /**
     * ID is the stable dockview panel id, so the persisted split layout can be
     * matched back to the right tab on restore. Empty for legacy entries.
     */
    "id": string;
    "title": string;
    "accent": string;

    /**
     * Pwd is the tab's last-known working directory; the restored shell boots
     * here instead of the user's home directory. Empty means home.
     */
    "pwd": string;
}
