// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionInfo is the wire-safe view of a session, shared by the Wails
 * bindings and the MCP tools.
 */
export interface SessionInfo {
    "id": string;
    "title": string;
    "window": string;
    "running": boolean;
    "created_at": string;
    "cols": number;
    "rows": number;
    "pwd": string;
}
