// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService runs the MCP server that lets AI clients drive pwsh sessions.
 * 
 * Two transports are supported:
 *   - streamable-HTTP on 127.0.0.1 (GUI mode, toggle from the MCP page)
 *   - stdio via `pwsh-mcp.exe --mcp` (headless, for classic client configs)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Disable stops the HTTP MCP server and persists the choice.
 */
export function Disable(): $CancellablePromise<void> {
    return $Call.ByID(3112910464);
}

/**
 * Enable starts the streamable-HTTP MCP server on the given loopback port and
 * persists the choice. Restarting on a new port is allowed while running.
 */
export function Enable(port: number): $CancellablePromise<void> {
    return $Call.ByID(3902656803, port);
}

/**
 * GetStatus reports the MCP server state for the management UI.
 */
export function GetStatus(): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(2433951426);
}

/**
 * Shutdown stops the HTTP server on application exit.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(20376910);
}
