// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPStatus is the state reported to the management UI.
 */
export interface MCPStatus {
    "running": boolean;
    "url": string;
    "port": number;
    "tool_count": number;
    "tools": ToolInfo[] | null;
    "stdio_cmd": string;
}

/**
 * ToolInfo describes an exposed MCP tool for the management UI.
 */
export interface ToolInfo {
    "name": string;
    "description": string;
}
