// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MCPStatus is the state reported to the management UI.
 */
export class MCPStatus {
    "running": boolean;
    "url": string;
    "port": number;
    "tool_count": number;
    "tools": ToolInfo[];
    "stdio_cmd": string;

    /** Creates a new MCPStatus instance. */
    constructor($$source: Partial<MCPStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("tool_count" in $$source)) {
            this["tool_count"] = 0;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("stdio_cmd" in $$source)) {
            this["stdio_cmd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPStatus {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField4_0($$parsedSource["tools"]);
        }
        return new MCPStatus($$parsedSource as Partial<MCPStatus>);
    }
}

/**
 * ToolInfo describes an exposed MCP tool for the management UI.
 */
export class ToolInfo {
    "name": string;
    "description": string;

    /** Creates a new ToolInfo instance. */
    constructor($$source: Partial<ToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo($$parsedSource as Partial<ToolInfo>);
    }
}

// Private type creation functions
const $$createType0 = ToolInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
