// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionManager manages a set of interactive pwsh sessions, each running inside
 * its own Windows ConPTY, so shells behave exactly like a real terminal
 * (Tab completion, PSReadLine, progress bars, Ctrl+C, ...). Every window owns
 * one session, and MCP clients can create and drive additional sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BindSessionWindow rebinds an existing session to another window, so closing
 * that window stops the session.
 */
export function BindSessionWindow(id: string, windowName: string): $CancellablePromise<void> {
    return $Call.ByID(25511881, id, windowName);
}

/**
 * ListSessions returns all sessions, oldest first.
 */
export function ListSessions(): $CancellablePromise<$models.SessionInfo[] | null> {
    return $Call.ByID(2993210509);
}

/**
 * ReadOutput returns output buffered since the given byte offset. Use the
 * returned NextOffset for follow-up calls; offset 0 returns recent history.
 */
export function ReadOutput(id: string, since: number): $CancellablePromise<[string | null, number, boolean]> {
    return $Call.ByID(3812374817, id, since);
}

/**
 * Resize informs the ConPTY of the terminal's new dimensions so pwsh reflows
 * its layout. Called by the frontend whenever xterm.js is resized.
 */
export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2966515760, id, cols, rows);
}

/**
 * ShutdownAll closes every session; used on application exit.
 */
export function ShutdownAll(): $CancellablePromise<void> {
    return $Call.ByID(244979753);
}

/**
 * StartSession launches a new pwsh inside a ConPTY and registers it.
 * windowName associates the session with a GUI window so it can be cleaned up
 * when that window closes (may be empty for MCP-only sessions). workDir sets
 * the shell's initial working directory ("" = the user's home directory; a
 * path that no longer exists also falls back to home).
 */
export function StartSession(windowName: string, workDir: string): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(2696017376, windowName, workDir);
}

/**
 * StopSession terminates a session's ConPTY and shell, then forgets it.
 */
export function StopSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1653264108, id);
}

/**
 * StopSessionsForWindow closes every session bound to the named window.
 * Called when a window closes so its shell does not leak.
 */
export function StopSessionsForWindow(windowName: string): $CancellablePromise<void> {
    return $Call.ByID(3738234052, windowName);
}

/**
 * WriteInput forwards keystrokes or pasted text to a session's stdin.
 * xterm.js delivers data (including escape sequences for arrows etc.) via its
 * onData callback, and we pass it through untouched.
 */
export function WriteInput(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3918180837, id, data);
}
