// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowInfo is the wire-safe view of an application window.
 */
export interface WindowInfo {
    "name": string;
    "title": string;
}
