// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowManager creates and tracks terminal windows. Every window loads the
 * same frontend, which then starts (or attaches) a pwsh session bound to the
 * window name.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseWindow closes the window with the given name (session cleanup runs via
 * the WindowClosing hooks).
 */
export function CloseWindow(name: string): $CancellablePromise<void> {
    return $Call.ByID(1926622052, name);
}

/**
 * GetTabPrefs returns the persisted terminal tab layout (title + accent per
 * tab). Sessions themselves are not persisted — each tab boots a fresh shell.
 */
export function GetTabPrefs(): $CancellablePromise<config$0.TabPref[] | null> {
    return $Call.ByID(4140394843);
}

/**
 * HideToTray hides every window but keeps the app (sessions + MCP server)
 * running in the background. The user restores it from the system tray icon.
 */
export function HideToTray(): $CancellablePromise<void> {
    return $Call.ByID(2433129125);
}

/**
 * ListWindows returns the application windows created by this service that
 * are still alive, ordered by name.
 */
export function ListWindows(): $CancellablePromise<$models.WindowInfo[] | null> {
    return $Call.ByID(4125795609);
}

/**
 * NewWindow opens a new terminal window and returns its identity. When the
 * window closes, sessions bound to it are stopped automatically.
 */
export function NewWindow(): $CancellablePromise<$models.WindowInfo | null> {
    return $Call.ByID(1230800302);
}

/**
 * QuitApp exits the whole application (all windows, sessions and the MCP
 * server). Used by the close dialog and the tray menu.
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(2116147254);
}

/**
 * SetTabPrefs persists the terminal tab layout so it is restored on the next
 * launch.
 */
export function SetTabPrefs(prefs: config$0.TabPref[] | null): $CancellablePromise<void> {
    return $Call.ByID(4166640591, prefs);
}

/**
 * ShowFromTray restores all windows and brings the primary one to the front.
 * Handles both tray-hidden windows (hidden via Hide() → need Show() to restore
 * the WebView2 surface) and taskbar-minimised windows (need UnMinimise()).
 */
export function ShowFromTray(): $CancellablePromise<void> {
    return $Call.ByID(4169838341);
}
