// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TabPref is the persisted UI state of one terminal tab (sessions themselves
 * are not restored — each tab boots a fresh shell on startup).
 */
export interface TabPref {
    "title": string;
    "accent": string;
}
