// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPStatus is the state reported to the management UI.
 */
export interface MCPStatus {
    "running": boolean;
    "url": string;
    "port": number;
    "tool_count": number;
    "tools": ToolInfo[] | null;
    "stdio_cmd": string;
}

/**
 * SessionInfo is the wire-safe view of a session, shared by the Wails
 * bindings and the MCP tools.
 */
export interface SessionInfo {
    "id": string;
    "title": string;
    "window": string;
    "running": boolean;
    "created_at": string;
    "cols": number;
    "rows": number;
}

/**
 * ToolInfo describes an exposed MCP tool for the management UI.
 */
export interface ToolInfo {
    "name": string;
    "description": string;
}

/**
 * WindowInfo is the wire-safe view of an application window.
 */
export interface WindowInfo {
    "name": string;
    "title": string;
}
