// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PwshService hosts an interactive pwsh session inside a Windows ConPTY, so the
 * shell behaves exactly like a real terminal (Tab completion, multi-line input,
 * progress bars, Ctrl+C, PSReadLine, ...).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Init binds the Wails app to the service.
 */
export function Init(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(702463625, app);
}

/**
 * Resize informs the ConPTY of the terminal's new dimensions so pwsh reflows
 * its layout. Called by the frontend whenever xterm.js is resized.
 */
export function Resize(cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(317579559, cols, rows);
}

/**
 * StartPwsh launches pwsh inside a ConPTY pseudo terminal.
 */
export function StartPwsh(): $CancellablePromise<void> {
    return $Call.ByID(4159944267);
}

/**
 * StopPwsh terminates the ConPTY and the shell inside it.
 */
export function StopPwsh(): $CancellablePromise<void> {
    return $Call.ByID(13408853);
}

/**
 * WriteInput forwards keystrokes or pasted text to the shell's stdin.
 * xterm.js delivers data (including escape sequences for arrows etc.) via its
 * onData callback, and we pass it through untouched.
 */
export function WriteInput(data: string): $CancellablePromise<void> {
    return $Call.ByID(2114214678, data);
}
