// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WindowInfo is the wire-safe view of an application window.
 */
export class WindowInfo {
    "name": string;
    "title": string;

    /** Creates a new WindowInfo instance. */
    constructor($$source: Partial<WindowInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo($$parsedSource as Partial<WindowInfo>);
    }
}
