// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowManager creates and tracks terminal windows. Every window loads the
 * same frontend, which then starts (or attaches) a pwsh session bound to the
 * window name.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseWindow closes the window with the given name (session cleanup runs via
 * the WindowClosing hooks).
 */
export function CloseWindow(name: string): $CancellablePromise<void> {
    return $Call.ByID(123397956, name);
}

/**
 * ListWindows returns the application windows created by this service that
 * are still alive, ordered by name.
 */
export function ListWindows(): $CancellablePromise<$models.WindowInfo[]> {
    return $Call.ByID(3813580153).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * NewWindow opens a new terminal window and returns its identity. When the
 * window closes, sessions bound to it are stopped automatically.
 */
export function NewWindow(): $CancellablePromise<$models.WindowInfo | null> {
    return $Call.ByID(2880287246).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WindowInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
