// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService runs the built-in AI assistant. It owns one Dive agent bound
 * to the SessionManager (so the agent's tools operate real terminal sessions)
 * and streams progress to every window through the agent_event Wails event.
 * Only one turn runs at a time; write commands pause for user approval unless
 * full-permission mode (autoApprove) is enabled.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * Approve resolves a pending approval request. approved=true runs the pending
 * command (for execute_command) or completes the action; approved=false
 * reports the user's rejection back to the agent. The turn resumes in a
 * goroutine.
 */
export function Approve(toolCallID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(2795429305, toolCallID, approved);
}

/**
 * Cancel aborts the in-flight turn, if any.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3938577874);
}

/**
 * GetLLMConfig returns the current model configuration.
 */
export function GetLLMConfig(): $CancellablePromise<config$0.LLMConfig> {
    return $Call.ByID(1108201857);
}

/**
 * IsAutoApprove reports whether full-permission mode is on: modifying
 * commands, raw input and session stops run without asking for approval.
 */
export function IsAutoApprove(): $CancellablePromise<boolean> {
    return $Call.ByID(1767888156);
}

/**
 * IsConfigured reports whether a model has been configured, plus a human
 * explanation of the state.
 */
export function IsConfigured(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(1393220912);
}

/**
 * LogFrontend lets the frontend write a diagnostic line into the agent log
 * (e.g. component mount/unmount or state transitions) so UI-only bugs can be
 * correlated with the backend event stream in a single file.
 */
export function LogFrontend(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2475040482, msg);
}

/**
 * SendMessage feeds a user message to the agent and returns immediately; the
 * turn runs in a goroutine and progress streams over agent_event. An error is
 * returned only when the message cannot start (busy, awaiting approval, or
 * not configured).
 */
export function SendMessage(input: string): $CancellablePromise<void> {
    return $Call.ByID(2587051541, input);
}

/**
 * SetAutoApprove toggles full-permission mode and persists the choice. It
 * emits a config event so every window's UI reflects the new state.
 */
export function SetAutoApprove(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2439028692, enabled);
}

/**
 * SetLLMConfig reconfigures the model provider and rebuilds the agent, then
 * persists the settings. Changing the model keeps the conversation memory.
 */
export function SetLLMConfig(cfg: config$0.LLMConfig): $CancellablePromise<void> {
    return $Call.ByID(439154213, cfg);
}
